name: Bluum
options:
  bundleIdPrefix: com.bluum
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

targets:
  Bluum:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
        excludes:
          - "*.md"
          - "*.txt"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bluum.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Sources/Bluum/Info.plist
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        SWIFT_VERSION: 5.0
        CLANG_ENABLE_MODULES: YES
        CLANG_ENABLE_OBJC_ARC: YES
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGNING_ALLOWED: NO
        OTHER_CODE_SIGN_FLAGS: "--deep"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: AVKit.framework
      - sdk: CoreMedia.framework
      - sdk: SwiftUI.framework
    info:
      path: Sources/Bluum/Info.plist
      properties:
        CFBundleName: Bluum
        CFBundleDisplayName: Bluum
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        LSApplicationCategoryType: "public.app-category.video"
        NSHighResolutionCapable: true
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication 